---
- name: Installs smartmontools
  apt:
    pkg: smartmontools
    state: present

- name: Install sudoers config to execute smartctl without password for telegraf
  template:
    src: 30-telegraf-smart.j2
    dest: "/etc/sudoers.d/30-telegraf-smart"
    mode: 0440
    group: root
    owner: root
