- name: Imports influxdb apt key
  apt_key: 
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Adds influxdb repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
    state: present
    update_cache: yes

- name: Installs telegraf
  apt:
    pkg: telegraf
    state: present

- name: Adds telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Adds input plugins configs
  template:
    src: input.generic.conf.j2
    dest: "/etc/telegraf/telegraf.d/{{ item.key }}.conf"
  with_dict: "{ {{ telegraf_inputs }} }"
  notify: Restart telegraf

- name: Add telegraf user in haproxy group if plugin is present
  user:
    name: telegraf
    groups: haproxy
    append: true
  when: '"haproxy" in telegraf_inputs'
  notify: Restart telegraf

